# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Penguinctl < Formula
  desc "Penguin CLI"
  homepage "https://github.com/vmware-tanzu-learning/penguinctl"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vmware-tanzu-learning/penguinctl/releases/download/v0.1.0/traverse_v0.1.0_darwin_amd64.tar.gz"
      sha256 "261fd2a6344a28f28ff9b62d056348ae7d79dd68d5db3c747d7f5305254b2be8"

      def install
        bin.install "penguinctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vmware-tanzu-learning/penguinctl/releases/download/v0.1.0/traverse_v0.1.0_darwin_arm64.tar.gz"
      sha256 "c5ef29bd7cf2c4bea7300e86a074011ad3501985cd327012c5f6241d24240bbc"

      def install
        bin.install "penguinctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vmware-tanzu-learning/penguinctl/releases/download/v0.1.0/traverse_v0.1.0_linux_arm64.tar.gz"
      sha256 "97de3e5f700029b61363c3d82053ac2167237c63a67deffa5187c978c8d9e1b4"

      def install
        bin.install "penguinctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vmware-tanzu-learning/penguinctl/releases/download/v0.1.0/traverse_v0.1.0_linux_amd64.tar.gz"
      sha256 "122be54a8d69769b8f6ba5d2c7357fa401f71f1ded1e268119bdc7594d92bc40"

      def install
        bin.install "penguinctl"
      end
    end
  end

  test do
    system "#{bin}/penguinctl --version"
  end
end
